Repository nunomaduro/phpinsights, pull requests merged in 2019-06, with the labels that each got.

#155 [Feat] Ignore blade files
  src/Infrastructure/Repositories/LocalFilesRepository.php
  tests/Infrastructure/Repositories/Fixtures/FolderWithBladeFile/login.blade.php
  tests/Infrastructure/Repositories/LocalFilesRepositoryTest.php
Labels: enhancement

#154 [Feat] Added support for Laravel attribute setters in Laravel preset
  .editorconfig
  phpstan.neon.dist
  phpunit.xml.dist
  src/Application/Adapters/Laravel/Preset.php
  src/Domain/Collector.php
  src/Domain/File.php
  src/Domain/Metrics/Code/Classes.php
  src/Domain/Sniffs/ForbiddenSetterSniff.php
  tests/Domain/Insights/ForbiddenSetterMethods/Fixtures/AnonymousClassWithSetter.php
  tests/Domain/Insights/ForbiddenSetterMethods/Fixtures/ClassWithLaravelAttributeSetter.php
  tests/Domain/Insights/ForbiddenSetterMethods/Fixtures/ClassWithNoSetter.php
  tests/Domain/Insights/ForbiddenSetterMethods/Fixtures/ClassWithSetter.php
  tests/Domain/Insights/ForbiddenSetterMethods/ForbiddenSetterMethodsTests.php
  tests/Fakes/FakeFileRepository.php
  tests/Feature/Laravel/ClassesTest.php
  tests/Feature/Laravel/Fixtures/ModelWithAttributeSetter.php
  tests/TestCase.php
Labels: enhancement

#167 Added "What other think about PHP Insights" page on the website
  docs/.vuepress/components/Testimonial.vue
  docs/.vuepress/config.js
  docs/.vuepress/style.styl
  docs/testimonial.md
Labels: enhancement

#168 Display InsightClass also when Insight has no detail
  src/Application/Console/Style.php
Labels: bug

#170 docs: explain how to config and list of used insights
  docs/.vuepress/config.js
  docs/insights/README.md
  docs/insights/architecture.md
  docs/insights/code.md
  docs/insights/complexity.md
  docs/insights/style.md
  docs/support.md
Labels: Docs

#182 [feat] Adds support for ignoring a file on a specific sniff
  phpstan.neon.dist
  src/Domain/EcsContainer.php
  src/Domain/File.php
  src/Domain/FileProcessor.php
  src/Domain/Insights/InsightCollectionFactory.php
  src/Domain/Insights/InsightFactory.php
  src/Domain/Insights/Sniff.php
  src/Domain/Sniffs/SniffWrapper.php
  tests/Domain/Sniffs/ForbiddenSetterMethods/ForbiddenSetterMethodsTest.php
  tests/Domain/Sniffs/SniffWrapperTest.php
  tests/Fixtures/Domain/Sniffs/SniffWrapper/FileWithTwoClasses.php
  tests/TestCase.php
Labels: enhancement

#188 [Docs] missing header + add concrete example for exclude file for Sniff
  docs/insights/README.md
  docs/insights/architecture.md
Labels: Docs

#190 Make the cyclomatic complexity limit configurable.
  docs/insights/complexity.md
  src/Domain/Insights/CyclomaticComplexityIsHigh.php
  tests/Domain/Insights/CyclomaticComplexityIsHighTest.php
  tests/Domain/Insights/Fixtures/LittleToComplexClass.php
  tests/Domain/Insights/Fixtures/NoCyclomaticComplexity.php
  tests/Domain/Insights/Fixtures/VeryMuchToComplexClass.php
Labels: enhancement

#195 Authorize analyse of one file or specific directory
  docs/get-started.md
  src/Application/Console/Commands/AnalyseCommand.php
  src/Domain/Insights/InsightCollectionFactory.php
  src/Domain/Kernel.php
  src/Infrastructure/Repositories/LocalFilesRepository.php
  tests/Infrastructure/Repositories/Fixtures/FileToInspect.php
  tests/Infrastructure/Repositories/LocalFilesRepositoryTest.php
Labels: enhancement

#196 Fix default preset "use in annotation" and fix merge config
  src/Application/Adapters/Drupal/Preset.php
  src/Application/Adapters/Laravel/Preset.php
  src/Application/Adapters/Magento2/Preset.php
  src/Application/Adapters/Symfony/Preset.php
  src/Application/Adapters/Yii/Preset.php
  src/Application/ConfigResolver.php
  src/Application/DefaultPreset.php
  src/Domain/Exceptions/PresetNotFound.php
  tests/Application/ConfigResolverTest.php
Labels: bug

#197 Fixes non defined key on config resolver
  src/Application/ConfigResolver.php
Labels: bug
